name: "AI Code Review"

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # THIS IS WHERE YOUR CUSTOM ACTION IS CALLED!
      - name: Gemini PR Reviewer
        uses: vivek180905/Gemini-AI-PR-Reviewer@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
